### ISSUE TITLE
Move to koa-session

### ISSUE THREAD

**Issue by lukeramsden** [koajs/userauth#24]
https://github.com/koajs/session is now the normal session store

**Comment by mahnunchik** [comment]
Any news?

**Comment by dead-horse** [comment]
you can use koa-session replace koa-generic-session, this package only dependent on `ctx.session` exist.

**Comment by mahnunchik** [comment]
@dead-horse maybe there is sense to update readme https://github.com/koajs/userauth#usage

**Comment by dead-horse** [comment]
Welcome to open a PR to fix the README. :)
