### ISSUE TITLE
are there any examples beyond the usage example?

### ISSUE THREAD

**Issue by soundyogi** [koajs/userauth#4]
I am kinda to stupid ti get ohe usage of this, especially all that redirect url stuff...

Could you provide a little example for idiots?

thx ^^;

**Comment by lukasT** [comment]
neither did I.... +1 for the example for idiots :)

**Comment by fengmk2** [comment]
I will draw a flow image which try to explain how `userauth` work...

**Comment by fengmk2** [comment]
![](https://www.lucidchart.com/publicSegments/view/54ede075-87a4-4118-84c6-79e20a004805/image.png)

**Comment by soundyogi** [comment]
Thx! That really cleared it up, much more sophisticated than I thougt
